---
openapi: 3.0.0
info:
  title: Teedy Acceptance API
  description: ML Grad Student Predicition API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/kellikuramoto/hw4-e4/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://127.0.0.1:5000
  description: SwaggerHub API Auto Mocking
paths:
  /predict_on_study:
    get:
      summary: Predicts the acceptance of a Grad Student candiate based off study criteria
      parameters:
      - name: G1
        in: query
        description: first period grade
        required: false
        style: form
        explode: true
        schema:
          maximum: 20
          minimum: 0
          type: integer
          format: int32
      - name: G2
        in: query
        description: second period grade
        required: false
        style: form
        explode: true
        schema:
          maximum: 20
          minimum: 0
          type: integer
          format: int32
      - name: failures
        in: query
        description: number of past class failures
        required: false
        style: form
        explode: true
        schema:
          maximum: 4
          minimum: 1
          type: integer
          format: int32
      responses:
        "200":
          description: Calls ML model to make prediction based off of study characteristics
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Bad input parameter
        "500":
          description: Internal server error
components: {}
